fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /security

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /security

mixstore_user_board:
    pattern: /board
    defaults: { _controller: MixstoreUserBundle:Board:index }


mixstore_user_admin_setsa:
    pattern: /setsa
    defaults: { _controller: MixstoreUserBundle:MyAdmin:setsa }

mixstore_user_admin_users:
    pattern: /admin/users
    defaults: { _controller: MixstoreUserBundle:MyAdmin:users }

mixstore_user_admin_toggle:
    pattern: /admin/toggle
    defaults: { _controller: MixstoreUserBundle:MyAdmin:toggle }

mixstore_user_admin_delete:
    pattern: /admin/delete/{id}
    defaults: { _controller: MixstoreUserBundle:MyAdmin:delete }
    requirements:
        id: \d+

mixstore_user_admin_addlanguage:
    pattern: /admin/addLanguage/{lgname}
    defaults: { _controller: MixstoreUserBundle:MyAdmin:addLanguage }

mixstore_user_admin_setlanguage:
    pattern: /admin/setLanguage
    defaults: { _controller: MixstoreUserBundle:MyAdmin:setLanguage }
